version: "2"
services: 
  db:
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: mypass
  web: 
    build: "."
    depends_on: 
      - db
    environment: 
      DATABASE_URL: "postgres://myuser:mypass@db:5432"
    ports: 
      - "8000:3000"
    volumes: 
      - ".:/code"
