version: "2"
services: 
  db:
    image: postgres:latest
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass

    expose:
    - 5432
    ports:
    - "1234:5432"
  web: 
    build: "."
    depends_on: 
      - db
    environment: 
      DATABASE_URL: "postgres://postgres:mypass@db:5432"
    ports: 
      - "8000:3000"
    volumes: 
      - ".:/code"
